### ISSUE TITLE
프로젝트 시작관련 이슈 해결

### ISSUE THREAD

**Issue by limchanghoon** [hchbae1001/team17_tetris#10]
프로젝트 시작관련 이슈 해결버전 545ef5326c70015a15ace46cca957596fff0f811
시작 프로그램 project 폴더에 내장 / 시작 문제로 인한 tetris -> Tetris로 이름변경

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [게임로직](https://trello.com/c/QhxVhX2z/3-%EA%B2%8C%EC%9E%84%EB%A1%9C%EC%A7%81)
