### ISSUE TITLE
스피드 버그 관련 수정버전

### ISSUE THREAD

**Issue by limchanghoon** [hchbae1001/team17_tetris#11]
스피드 버그 관련 수정버전 a366ab638eb4fdef7000337044269c188585acd9
최종 속도를 넘어가 속도가 끝없이 올라가는 버그 수정

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [게임로직](https://trello.com/c/QhxVhX2z/3-%EA%B2%8C%EC%9E%84%EB%A1%9C%EC%A7%81)
