### ISSUE TITLE
리더보드 첫 구현

### ISSUE THREAD

**Issue by limchanghoon** [hchbae1001/team17_tetris#12]
리더보드 첫 구현 4209d964f00b9f800bf32c54ad0ca6deddeb0554

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [스코어 보드](https://trello.com/c/DW4zYKkg/17-%EC%8A%A4%EC%BD%94%EC%96%B4-%EB%B3%B4%EB%93%9C)
