### ISSUE TITLE
리더보드 2차 수정 버전

### ISSUE THREAD

**Issue by limchanghoon** [hchbae1001/team17_tetris#13]
리더보드 2차 수정 버전 fc06da924de159668b51c5f63521eee4c16fde8d

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [스코어 보드](https://trello.com/c/DW4zYKkg/17-%EC%8A%A4%EC%BD%94%EC%96%B4-%EB%B3%B4%EB%93%9C)
