### ISSUE TITLE
블럭을 텍스트 형식으로 변경한 버전

### ISSUE THREAD

**Issue by limchanghoon** [hchbae1001/team17_tetris#14]
블럭을 텍스트 형식으로 변경한 버전 abfd4f643df16e7b3fea4f7bc06f2142279a31c2

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [게임로직](https://trello.com/c/QhxVhX2z/3-%EA%B2%8C%EC%9E%84%EB%A1%9C%EC%A7%81)
