### ISSUE TITLE
리더 보드를 합친 후 점수 표시 버그 수정 버전

### ISSUE THREAD

**Issue by limchanghoon** [hchbae1001/team17_tetris#15]
리더 보드를 합친 후 최종에 점수가 다르게 표시되는 버그 수정 버전 a36e945b802906abd62bdf30726dbb5096113cb8 
버그 수정과 함께 잘못 삽입된 코드 수정 버전(이번 이슈의 최종) 865e611ffa85f34fea6814c3347abf03f50997dc

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [스코어 보드](https://trello.com/c/DW4zYKkg/17-%EC%8A%A4%EC%BD%94%EC%96%B4-%EB%B3%B4%EB%93%9C)
