### ISSUE TITLE
Setting page 구현 버전 

### ISSUE THREAD

**Issue by limchanghoon** [hchbae1001/team17_tetris#21]
Form class / public static colorBlindMode 접근하여
색각이상자 모드 On Off 가능
//Todo - 키변경 사이즈변경 스코어보드초기화 설정초기화
https://github.com/hchbae1001/team17_tetris/commit/056b0d9459e9ba6c7edaaa752c09572e9c373840

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [스타트메뉴](https://trello.com/c/gCktewMS/6-%EC%8A%A4%ED%83%80%ED%8A%B8%EB%A9%94%EB%89%B4)

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [설정](https://trello.com/c/QHNvMSLx/5-%EC%84%A4%EC%A0%95)
