### ISSUE TITLE
아래로 한칸 내리기 추가, 난이도 추가, 확률 검증 완료 버전

### ISSUE THREAD

**Issue by limchanghoon** [hchbae1001/team17_tetris#24]
74eb247293489fa51bac3bb5865fad6f2435f6fb
https://github.com/hchbae1001/team17_tetris/commit/2b9d4482c5c9a2fc83d8e3dbef13c981ffd08f1d

1. 아랫키로 한칸 내리기 추가, 끝까지 내리기는 Space키로 변경

2. EASY, NORMAL, HARD 난이도 추가했습니다.
EASY는 5000점 당 프레임 40감소,최대 속도는 300프레임, I형 블럭(OOOO)이 20% 더 자주 등장
NORMAL는 5000점 당 프레임 50감소, 최대 속도 200프레임, 확률 동등
HARD 는 5000점 당 프레임 60감소, 최대 속도 100프레임, I형 블럭(OOOO)이 20% 덜 등장

3. 요구사항에 있던 5% 오차범위 내 확률 테스트 100회 이상 완료했습니다.

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [게임로직](https://trello.com/c/QhxVhX2z/3-%EA%B2%8C%EC%9E%84%EB%A1%9C%EC%A7%81)
