### ISSUE TITLE
게임종료시 리더보드 출력

### ISSUE THREAD

**Issue by Seobok** [hchbae1001/team17_tetris#35]
게임이 종료되었을때 리더보드를 출력합니다. 
만약 10위 안에 들었다면 자신의 점수를 빨간색으로 강조합니다.
또, 게임시작전 리더보드를 확인한 후 게임종료시 리더보드를 출력할때 자신의 점수가 출력되지 않았던 오류를 해결하였습니다.
https://github.com/hchbae1001/team17_tetris/pull/34/commits/985a42b3c39f224bbcf8132157ac3acac38c2842

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [스코어 보드](https://trello.com/c/DW4zYKkg/17-%EC%8A%A4%EC%BD%94%EC%96%B4-%EB%B3%B4%EB%93%9C)
