### ISSUE TITLE
일시 정지, 계속하기, 다시 시작, 메인메뉴 가기, 종료 구현

### ISSUE THREAD

**Issue by limchanghoon** [hchbae1001/team17_tetris#41]
일시 정지, 계속하기, 다시 시작, 메인메뉴 가기, 종료 구현했습니다. 06738e71833252a53a507f5fb8b03badb02c93f4
메인 코드와 합친 버전 4d5b3691f66fb76a66aa0b5b087195f68cb3f440

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [게임로직](https://trello.com/c/QhxVhX2z/3-%EA%B2%8C%EC%9E%84%EB%A1%9C%EC%A7%81)

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [게임로직](https://trello.com/c/QhxVhX2z/3-%EA%B2%8C%EC%9E%84%EB%A1%9C%EC%A7%81)

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [인게임UI](https://trello.com/c/JxbwdzMh/2-%EC%9D%B8%EA%B2%8C%EC%9E%84ui)
