### ISSUE TITLE
모드별, 난이도별 스코어보드 구분

### ISSUE THREAD

**Issue by Seobok** [hchbae1001/team17_tetris#43]
https://github.com/hchbae1001/team17_tetris/pull/42/commits/3d950a6269f140db7d26d4745a1eb5664d3d849e
모드별, 난이도별 스코어보드 구분 했습니다.
코드가 지저분한데 추후 수정하도록 하겠습니다.

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [스코어 보드 로직](https://trello.com/c/6CbtpiWu/15-%EC%8A%A4%EC%BD%94%EC%96%B4-%EB%B3%B4%EB%93%9C-%EB%A1%9C%EC%A7%81)
