### ISSUE TITLE
마무리 작업 & 씬 이동 버그 수정

### ISSUE THREAD

**Issue by limchanghoon** [hchbae1001/team17_tetris#50]
https://github.com/hchbae1001/team17_tetris/commit/2143fbcac51f9b23431667296c6609f614461207
씬 이동시 윈도우 크기가 변경되지 않는 버그 수정함

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [게임로직](https://trello.com/c/QhxVhX2z/3-%EA%B2%8C%EC%9E%84%EB%A1%9C%EC%A7%81)
