### ISSUE TITLE
씬 크기 버그 수정 및 전반적 마무리

### ISSUE THREAD

**Issue by limchanghoon** [hchbae1001/team17_tetris#54]
9929498e5d41c595bc6d33603334d3b16c8cc4ff
씬 크기 버그 수정했습니다.
1886175e57542587fae46795c058ef1ef948809c
종료시 프로세스가 완전 종료되지 않던 버그 수정했습니다.

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [게임로직](https://trello.com/c/QhxVhX2z/3-%EA%B2%8C%EC%9E%84%EB%A1%9C%EC%A7%81)
