### ISSUE TITLE
대전모드 UI 제작

### ISSUE THREAD

**Issue by hchbae1001** [hchbae1001/team17_tetris#55]
Tetris 대전모드 아이템모드, 시간제한 모드 변수명 정해서 알려주세요!

9951296

**Comment by limchanghoon** [comment]
cpItemModeBool
cpToModeBool
어떤가요

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [대전모드](https://trello.com/c/Yo1ASWuZ/18-%EB%8C%80%EC%A0%84%EB%AA%A8%EB%93%9C)

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [대전모드](https://trello.com/c/Yo1ASWuZ/18-%EB%8C%80%EC%A0%84%EB%AA%A8%EB%93%9C)

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [인게임UI](https://trello.com/c/JxbwdzMh/2-%EC%9D%B8%EA%B2%8C%EC%9E%84ui)
