### ISSUE TITLE
대전모드 기본로직 추가

### ISSUE THREAD

**Issue by limchanghoon** [hchbae1001/team17_tetris#57]
123179d14f824a4f9829d1f71c8382d786b861f0
대전모드의 기본적인 로직을 추가했습니다. 일단 대전모드 일반만 추가한 상태입니다.

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [대전모드](https://trello.com/c/Yo1ASWuZ/18-%EB%8C%80%EC%A0%84%EB%AA%A8%EB%93%9C)

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [대전모드](https://trello.com/c/Yo1ASWuZ/18-%EB%8C%80%EC%A0%84%EB%AA%A8%EB%93%9C)
