### ISSUE TITLE
Attack block 바로 줄삭제시 버그

### ISSUE THREAD

**Issue by limchanghoon** [hchbae1001/team17_tetris#62]
https://github.com/hchbae1001/team17_tetris/pull/58/commits/ca2e2a85757c86e09b2dcba9863cb41c4d1e9365
Attack block이 나온 뒤 바로 줄삭제시 해당 줄 위의 줄이 큐에 들어가는 버그가 있습니다.
공격줄 생성과 P1_previous_MESH(P2_previous_MESH)에 값을 set하는 순서를 바꾸면 가능해보입니다

**Comment by Seobok** [comment]
https://github.com/hchbae1001/team17_tetris/commit/3ebdb29ef0adb88839f46b048027fc05763d53a5
수정 완료

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [대전모드](https://trello.com/c/Yo1ASWuZ/18-%EB%8C%80%EC%A0%84%EB%AA%A8%EB%93%9C)
