### ISSUE TITLE
아이템모드 플레이어 지정문제

### ISSUE THREAD

**Issue by Seobok** [hchbae1001/team17_tetris#63]
https://github.com/hchbae1001/team17_tetris/commit/3ebdb29ef0adb88839f46b048027fc05763d53a5
게임 시작하자마자 아이템모드로 게임시작시 cp가 제대로 설정되지 않는 문제가 발생

**Comment by Seobok** [comment]
https://github.com/hchbae1001/team17_tetris/commit/c2b887f2a7417c67c77a75ad353e42200a87275b
오류 수정

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [대전모드](https://trello.com/c/Yo1ASWuZ/18-%EB%8C%80%EC%A0%84%EB%AA%A8%EB%93%9C)

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [대전모드](https://trello.com/c/Yo1ASWuZ/18-%EB%8C%80%EC%A0%84%EB%AA%A8%EB%93%9C)

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [대전모드](https://trello.com/c/Yo1ASWuZ/18-%EB%8C%80%EC%A0%84%EB%AA%A8%EB%93%9C)
