### ISSUE TITLE
대전모드 시작 화면 위치 고정(기타 UI)

### ISSUE THREAD

**Issue by limchanghoon** [hchbae1001/team17_tetris#70]
대전모드 시작 화면 위치 고정
1P는 (0,0)으로
2P는 (모니터 X축해상도/2, 0)
https://github.com/hchbae1001/team17_tetris/pull/60/commits/7ae8bdf7a682b439f22193260a65b3976b7cc81c

**Comment by limchanghoon** [comment]
https://github.com/hchbae1001/team17_tetris/commit/01a04f9906eb3562513cf193b24addd38cce2e8f
인게임 다음 블럭과 공격 블럭의 테두리추가

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [인게임UI](https://trello.com/c/JxbwdzMh/2-%EC%9D%B8%EA%B2%8C%EC%9E%84ui)
