### ISSUE TITLE
대전모드에서 줄 삭제시 상대방 큐에 공격줄 표시

### ISSUE THREAD

**Issue by Seobok** [hchbae1001/team17_tetris#71]
대전모드에서 줄을 삭제하면 상대방이 바닥에 블럭을 놓음과 동시에 상대방의 공격줄이 생성이되며
생성되기 전까지는 옆에 작은 화면으로 출력해야함

**Comment by Seobok** [comment]
https://github.com/hchbae1001/team17_tetris/pull/58/commits/a3d1e92bf6d2fa629eedb7151b90aad04ff3bc79
기능추가

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [대전모드](https://trello.com/c/Yo1ASWuZ/18-%EB%8C%80%EC%A0%84%EB%AA%A8%EB%93%9C)
