### ISSUE TITLE
시간제한 모드 재시작, 싱글 아이템 모드 시작, 일반모드 공격 큐 적용 버그

### ISSUE THREAD

**Issue by limchanghoon** [hchbae1001/team17_tetris#73]
1. timer mode 재시작시 동작 안하는 버그 수정
2. 싱글아이템모드 시작시 오류 발생
3. 공격 큐 테두리 일반 모드에 적용된 버그

**Comment by limchanghoon** [comment]
1. https://github.com/hchbae1001/team17_tetris/commit/0ff4fff6eaf6c9da711c84158c27fc2e97266516 타이머 모드 재시작시 초기값이 누락돼서 버그 발생했습니다. 이를 수정하고 cp mode GameOver 호출과 input쓰레드에서 cpModeEnd 도시 호출 과정시 버그 발생하여 수정

2. https://github.com/hchbae1001/team17_tetris/pull/64/commits/c2b887f2a7417c67c77a75ad353e42200a87275b cp변수 초기값 설정을 해줌으로 해결

3. https://github.com/hchbae1001/team17_tetris/pull/67/commits/87d9d353ca34f553cbc19b5e2aead0040e95f176 일반 모드에서도 공격 큐를 group에 넣었던 부분 삭제함

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [대전모드](https://trello.com/c/Yo1ASWuZ/18-%EB%8C%80%EC%A0%84%EB%AA%A8%EB%93%9C)
