### ISSUE TITLE
게임 로직 1차 수정 버전

### ISSUE THREAD

**Issue by limchanghoon** [hchbae1001/team17_tetris#8]
게임 로직 1차 수정 버전 e1a67a98a857cfa1cf7286e1258183be36a1f530

**Comment by hchbae1001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [게임로직](https://trello.com/c/QhxVhX2z/3-%EA%B2%8C%EC%9E%84%EB%A1%9C%EC%A7%81)
